
FROM python:3.9-slim

# switch working directory
WORKDIR /app

# copy the requirements file into the image
COPY requirements.txt /app/

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app/

#Expose Application Port
EXPOSE 5000

CMD ["python","app.py"]